SkyRoad_for_Drone/SkyRoad_for_Drone/urls.py
from django.contrib import admin
from django.urls import path, include
import single_pages

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')),
]

SkyRoad_for_Drone/single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.control_drone),
    path('add_drone/', views.path_planning)
]

SkyRoad_for_Drone/single_pages/models.py
from django.db import models

# Create your models here.

# class startModel():
#     start_field = models.AutoField(primary_key=True)
#     goal_field = models.AutoField(primary_key=True)

SkyRoad_for_Drone/single_pages/forms.py
from django import forms
import pymysql
import pandas as pd
# from models import startModel


# cluster = None

conn = pymysql.connect(host='34.64.132.212', user='root', password='ASewetsvc124~1242#%1wsdeWXV', db='source')
sql_state='SELECT * FROM `군집화된병원6`'
hospital = pd.read_sql_query(sql_state, conn)

START_CHOICES = [
    ('None','===출발지선택==='),
	('서울동부혈액원', '서울동부혈액원'),
    ('서울남부혈액원', '서울남부혈액원'),
    ('서울중앙혈액원', '서울중앙혈액원'),
    ('서울특별시보라매병원', '보라매병원'),
    ('재단법인아산사회복지재단서울아산병원', '서울아산병원'),
    ('학교법인연세대학교의과대학세브란스병원', '연세대학교세브란스병원'),
]

GOAL_CHOICES = [
        ('None','===도착지선택===')]
# targets = hospital.기관명.tolist()
# for i in targets:
#     GOAL_CHOICES.append((i,i))
 

class startForm(forms.Form):
    # class Meta:
    start_field = forms.ChoiceField( label="출발지", choices=START_CHOICES, widget = forms.Select(attrs = {'onchange':'selectgoals(this.value);','required':True,'class':'bootstrap-select'}))
    goal_field = forms.ChoiceField( label="도착지", choices=GOAL_CHOICES, widget = forms.Select(attrs = {'required':True,'class':'bootstrap-select'}))

SkyRoad_for_Drone/single_pages/views.py
# Create your views here.
# from __future__ import unicode_literals
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views import View
from django.shortcuts import redirect, render
from .forms import startForm
import pymysql
import pandas as pd
import numpy as np
import json
from fiona.crs import from_epsg
import geopandas as gpd
from keplergl import KeplerGl
from sqlalchemy import create_engine
from shapely.geometry.polygon import Polygon,LineString
from datetime import datetime, timedelta, timezone
import os
import warnings
from haversine import haversine
warnings.filterwarnings('ignore')

# 실행용 경로 drive/MyDrive/"팀 프로젝트"/"3차 프로젝트"/작업물/조남현/SkyRoad_for_Drone

# mountain_path = '/content/drive/MyDrive/"팀 프로젝트"/"3차 프로젝트"/작업물/조남현/SkyRoad_for_Drone/dataset'
mountain_path = 'dataset'
# array_path = '/content/drive/MyDrive/"팀 프로젝트"/"3차 프로젝트"/작업물/조남현/SkyRoad_for_Drone/dataset'
array_path = 'dataset'

global trip_count
global trip_multi
trip_count = 0
trip_multi = dict(type="FeatureCollection", features=[])

class service_window:
  #데이터 베이스에서 해당이름의 데이터 가져오기
  @staticmethod
  def load_db_data(name):
    conn = pymysql.connect(host='34.64.132.212', user='root', password='ASewetsvc124~1242#%1wsdeWXV', db='source')
    sql_state=f'SELECT * FROM `{name}`'
    name=pd.read_sql_query(sql_state, conn)
    return name

  #경계값을 지나는 장애물 검출하기
  @staticmethod
  def check_intersects(df,df1,poly):
    #pandas의 경우 데이터 타입을 geometry로 변경
    df['geometry'] = gpd.GeoSeries.from_wkt(df['geometry'])
    df = gpd.GeoDataFrame(df, geometry=df['geometry'])
    df['within']=df[['geometry']].intersects(poly)
    df=df.loc[df['within']==True]

    #geometry 타입은 그대로 검출에 사용
    df1['within']=df1[['geometry']].intersects(poly)
    df1=df1.loc[df1['within']==True]
    return df, df1

  # 병원,빌딩,드론 공항 불러오기
  @staticmethod
  def load_data():
    hospital=service_window.load_db_data("군집화된병원6")
    building=service_window.load_db_data("building_final")
    blood=service_window.load_db_data("드론공항위치")

    #산의 데이터 불러오기
    mountain = gpd.read_file(f'{mountain_path}/11.shp', encoding='euc-kr')
    mountain=mountain[['geometry']]
    mountain=mountain.to_crs(epsg=4326)
    mountain=mountain.drop(697)

    return hospital, building, blood, mountain

  # 고도를 고려한 경로의 추가
  @staticmethod
  def set_path(data_):
    data=[]
    for i in range(len(data_)):
      if i==0:
        data.append(data_[i])
        data.append(data_[i])
      elif i == len(data_)-1:
        data.append(data_[i])
        data.append(data_[i])
        data.append(data_[i])
      else:
        data.append(data_[i])

      path=pd.DataFrame(columns=['s_x','s_y','e_x','e_y'],data=data)

      #고도를 고려한 경로한 시작좌표와 도착좌표 변경
      path['e_x'][0] = path['s_x'][0]
      path['e_y'][0] = path['s_y'][0]
      # path['e_x'][1] = path['s_x'][1]
      # path['e_y'][1] = path['s_y'][1]

      path['s_x'][len(path)-2] = path['e_x'][len(path)-2]
      path['s_y'][len(path)-2] = path['e_y'][len(path)-2]
      path['s_x'][len(path)-1] = path['e_x'][len(path)-1]
      path['s_y'][len(path)-1] = path['e_y'][len(path)-1]

    return path

  # (line)경로 만들기
  @staticmethod
  def get_path(start,target):
    data = service_window.load_array(start,target)
    data = service_window.set_path(data)

    return data

  # 시간의 흐름에 따른 경로 만들기
  @staticmethod
  def get_path_trip(path):

    global trip_count 
    global trip_multi
   
    # 시작좌표와 도착좌표를 Point로 변경
    path['start'] = list(zip(path['s_y'], path['s_x']))
    path['end'] = list(zip(path['e_y'], path['e_x']))

    # 위에서 구한 Point를 Line으로 변경
    path['line'] = path.apply(lambda row : LineString([row['start'], row['end']]), axis=1)

    # 좌표간의 거리 추가를 위한 초기값 생성
    path['length']=0

    # 단위를 M로한 시작좌표와 도착좌표의 실제 거리
    for i in range(2,len(path)-2):
      path['length'][i] = haversine(path['start'][i], path['end'][i], unit = 'm')

    path = path[['s_x','s_y','length']]

    # 지표면에서 50미터 위로 다니기에 해당 길이는 50미터로 설정
    path['length'][1] = 50
    path['length'][len(path)-2] = 50 

    # 드론 속도를 고려한 초속 속도 
    speed = 70000 #70000m/h
    second_speed = speed/3600 

    # 길이를 초속으로 나누어 걸리는 시간을 구함
    # 상승과 하강은 1m/s 이므로 임의로 변경
    path['time'] = path['length'] / second_speed
    path['time'][0]=50
    path['time'].iloc[-2]=50

    # google colab에서 시간차이가 9시간 걸림
    now = datetime.now()+timedelta(hours=9)
    current = now.timestamp()
    
    # 현재시간을 구함
    path['datetime']=0
    path['datetime'][0]=current

    # 현재시간을 기준으로 해서 해당 좌표에서의 시간을 계산
    for i in range(1,len(path)):
      path['datetime'][i]=path['datetime'][i-1]+path['time'][i-1]

    path['trip_id'] = trip_count
    trip_count = trip_count+1
    print(trip_count)

    # 효과적인 시각화를 위해 높이는 300으로 설정 -> 실제 값은 해당 고도값 (50) 
    path['altitude']=300
    path['altitude'][0]=0
    path['altitude'].iloc[-1]=0

    #시작 도착 좌표 오차주기 -> 시각화 툴에서 같은 좌표에서의 높이 변경은 오차가 있어야 표현됨
    path['s_x'][0] = path['s_x'][0]-0.0001
    path['s_y'][0] = path['s_y'][0]-0.0001
    path['s_x'][len(path)-1] = path['s_x'][len(path)-1]-0.0001
    path['s_y'][len(path)-1] = path['s_y'][len(path)-1]-0.0001

    # 걸리는 시간과 도착시 시간을 구함
    elapsed_time = path['datetime'][len(path)-1]-path['datetime'][0]
    arrival_time = path['datetime'][len(path)-1]

    d = datetime.fromtimestamp(arrival_time)
    arrival_time=d.strftime("%X")

    # 데이터 삽입을 위한 그룹 타입으로 데이터 변경
    geo_json = dict(type="FeatureCollection", features=[])
    geo_json["features"]
    for trip in path.trip_id.unique():
      feature = dict(type="Feature", geometry=None, properties=dict(trip_id=str(trip)))
      feature["geometry"] = dict(type="LineString", coordinates=path.loc[path.trip_id==trip, ["s_x", "s_y", "altitude", "datetime"]].to_records(index=False).tolist())
      geo_json["features"].append(feature)
    trip_multi["features"].append(feature)

    return geo_json, elapsed_time, arrival_time

  #카카오 api
  @staticmethod
  def knavi(rest_api_key, origin, destination, priority = 'RECOMMEND'):
    import json
    import requests
    
    headers = {"Authorization": f"KakaoAK {rest_api_key}"}
    url = f"https://apis-navi.kakaomobility.com/v1/directions?origin={origin}&destination={destination}&waypoints=&priority={priority}&car_fuel=GASOLINE&car_hipass=false&alternatives=false&road_details=false"
    
    res = requests.get(url, headers=headers)
    document = json.loads(res.text)

    return document

  # 시각화 시간을 단축을 위한 카카오 api를 활용한 바운더리 얻기
  @staticmethod
  def kakao_boundary(blood,hospital):

    rest_api_key = '41239f1ad95324b1d51bf118d1e84251'

    origin = str(blood['경도'][0])+ ', '+str(blood['위도'][0])
    destination = str(hospital['경도'][0])+ ', '+str(hospital['위도'][0])

    temp = service_window.knavi(rest_api_key, origin, destination)
    max_x,max_y,min_x,min_y = list(temp['routes'][0]['summary']['bound'].values())
    new_boundary =[[min_x,min_y],[max_x,min_y],[max_x,max_y],[min_x,max_y],[min_x,min_y]]
    polygon = Polygon(new_boundary)
    return polygon, temp

  # DQN과 RRT를 활용한 좌표값 가져오기
  @staticmethod
  def load_array(start,target):
    import numpy as np
    
    if start == "서울동부혈액원":
      start = 'clu0'
    elif start == "재단법인아산사회복지재단서울아산병원":
      start = 'clu1'
    elif start == "서울특별시보라매병원":
      start = 'clu2'
    elif start == "학교법인연세대학교의과대학세브란스병원":
      start = 'clu3'
    elif start == "서울남부혈액원":
      start = 'clu4'
    elif start == "서울중앙혈액원":
      start = 'clu5'
    
    path = f"{array_path}/{start}_{target}.npy"
    array = np.load(path)
    return array

  # 지도 생성
  @staticmethod
  def create_map(start_, target_):
    # 데이터 불러오기
    hospital, building, blood, mountain = service_window.load_data()

    #시작지와 도착지 이름
    start = start_
    target = target_

    #해당되는 영역의 데이터
    blood = blood.loc[blood['기관명']==start].reset_index()
    hospital = hospital.loc[hospital['기관명']==target].reset_index()
    polygon,temp = service_window.kakao_boundary(blood,hospital)
    building, mountain = service_window.check_intersects(building,mountain, polygon)

    # 경로와 필요한 변수 산출
    path = service_window.get_path(start,target)
    trip, elapsed_time, arrival_time = service_window.get_path_trip(path)

    path = path[['s_x','s_y','e_x','e_y']]
    setting = service_window.kepler_set(start,target)

    # 지도에 데이터 삽입
    map = KeplerGl(height=600, width=500)
    map.add_data(data=hospital, name= "hospital")
    map.add_data(data=building, name= "building")
    map.add_data(data=blood, name= "blood")
    map.add_data(data=mountain, name='mountain')
    map.add_data(data=path, name= "path")
    map.add_data(data=trip, name='trip')
    map.config = setting

    arrival_time = datetime.strptime(arrival_time, '%H:%M:%S')
    arrival_time -= timedelta(hours=9)
    arrival_time = arrival_time.strftime('%H:%M:%S')
    
    return map, elapsed_time, arrival_time

  # 카카오 api에서 얻을수 있는 자동차 경로 좌표
  @staticmethod
  def kakao_path(temp):
    path_list=[]
    for i in range(0,len(temp['routes'][0]['sections'][0]['guides'])-1):
      s_x = temp['routes'][0]['sections'][0]['guides'][i]['x']
      s_y = temp['routes'][0]['sections'][0]['guides'][i]['y']
      t_x = temp['routes'][0]['sections'][0]['guides'][i+1]['x']
      t_y = temp['routes'][0]['sections'][0]['guides'][i+1]['y']
      path_list.append([s_x,s_y,t_x,t_y])
    
    path = get_path(path_list)
    path = path[['s_x','s_y','e_x','e_y']]
    return path

  #시작점과 도착점의 좌표
  @staticmethod
  def get_corrdinate(start_,target_):
    hospital, building, blood, mountain = service_window.load_data()
    start = start_
    target = target_

    blood = blood.loc[blood['기관명']==start].reset_index()
    hospital = hospital.loc[hospital['기관명']==target].reset_index()
    
    b_x = blood['경도'][0]
    b_y = blood['위도'][0]

    h_x = hospital['경도'][0]
    h_y = hospital['위도'][0]

    return b_x,b_y,h_x,h_y

  # 시각화시 좌표값을 고려한 세팅값을 가져옴
  @staticmethod
  def kepler_set(start_,target_):

    b_x,b_y,h_x,h_y = service_window.get_corrdinate(start_,target_)

SkyRoad_for_Drone/single_pages/templates/single_pages/base.html
<!DOCTYPE html>
<html lang="kr">

<head>
     <title>SkyRoad_for_drone</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css" />
     <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
     <script>
          function selectgoals(value){
               var start_select = $('#id_start_field').val();
               var changeItem = JSON.parse("{{ goals|escapejs }}")[start_select];
               $('#id_goal_field').empty();
               for(var count=0; count < changeItem.length; count++){
                    var option = $("<option>"+changeItem[count]+"</option>");
                    $('#id_goal_field').append(option);
               }
               }
     </script>
</head>
<style>
     #Title{
          text-align: center;
     }
     #menu{
          float: left;
     }
     #info{
          float: right;
     }
</style>

<body>
     <div id = "Title">
          <h2> 드론 관제 시스템 예시 </h2>
     </div>
     <div class="container-fluid">
          <div class="row">
               {% include 'single_pages/base_main.html' %}
               <div class="col-lg-12" id = "menu">
                    &nbsp; <a href='http://127.0.0.1:8000/add_drone'>드론 추가하기</a>
               </div>
          </div>
     </div>
</body>

</html>

SkyRoad_for_Drone/single_pages/templates/single_pages/base_origin.html
<!DOCTYPE html>
<html lang="kr">

<head>
     <title>SkyRoad_for_drone</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css" />
     <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
     <script>
          function selectgoals(value){
               var start_select = $('#id_start_field').val();
               var changeItem = JSON.parse("{{ goals|escapejs }}")[start_select];
               $('#id_goal_field').empty();
               for(var count=0; count < changeItem.length; count++){
                    var option = $("<option>"+changeItem[count]+"</option>");
                    $('#id_goal_field').append(option);
               }
               }
     </script>
</head>
<style>
     #Title{
          text-align: center;
     }
     #menu{
          float: left;
     }
     #info{
          float: right;
     }
</style>

<body>
     <div id = "Title">
          <h2> 드론 추가 화면 예시 </h2>
     </div>
     <div class="container-fluid">
          <div class="row">
               {% include 'single_pages/base_origin_main.html' %}
               <div class="col-lg-12" id = "menu">
                    <form method = "POST">
                         {% csrf_token %}
                         {{ form }}
                         <input type = "submit" value = "경로계산" >
                         <a href='http://127.0.0.1:8000/'>돌아가기</a>
                    </form>
               </div>
          </div>
     </div>
</body>

</html>

SkyRoad_for_Drone/single_pages/templates/single_pages/path.html
<!DOCTYPE html>
<html lang="kr">

<head>
     <title>SkyRoad_for_drone</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css" />
     <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
     <script>
          function selectgoals(value){
               var start_select = $('#id_start_field').val();
               var changeItem = JSON.parse("{{ goals|escapejs }}")[start_select];
               $('#id_goal_field').empty();
               for(var count=0; count < changeItem.length; count++){
                    var option = $("<option>"+changeItem[count]+"</option>");
                    $('#id_goal_field').append(option);
               }
               }
     </script>
</head>
<style>
     #Title{
          text-align: center;
     }
     #menu{
          float: left;
     }
     #info{
          background-color: #FFFFF0;
          color: rgb(0,10,130);
          float: right;
     }
</style>

<body>
     <div id = "Title">
          <h2> 드론 추가 화면 예시 </h2>
     </div>
     <div class="container-fluid">
          <div class="row">
               <div class="col-lg-12" id = "menu">
                    <form method = "POST">
                         {% csrf_token %}
                         {{ form }}
                         <input type = "submit" value = "경로계산">
                         <a href='http://127.0.0.1:8000/'>메인으로 돌아가기</a>
                         <div id = "info">
                              <h5>예상 소요시간: {{ elapsed_time }}   /   예상 도착시간: {{ arrival_time }}</h5>
                         </div>
                    </form>
               </div>
               {% include 'single_pages/path_new.html' %}
          </div>
     </div>
     
</body>
</html>